<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class formatoA extends Model
{

    protected $fillable = [
        'inaidempleado',
        'inaruido',
        'inafrio',
        'inacalor',
        'inaairefresco',
        'inaluz',
        'inacomodo',
        'inasustanquimicas',
        'inaesfuerzofisico',
        'inaequiposcomodos',
        'inaanimalesplantas',
        'inapreoaccidente',
        'inalugarlimpio',
        'inatiempoadicional',
        'inaalcanzatiempo',
        'inatrabajasinparar',
        'inaesfuerzomental',
        'inaexigeconcentrado',
        'inaexigememoria',
        'inadesiciondificiles',
        'inaexigeasuntos',
        'inapqnosdetalles',
        'inaresponcosasvalor',
        'inarespondinero',
        'inareponderotros',
        'inaresponarea',
        'inareponsalud',
        'inaordecontradic',
        'inahacerinnecesaria',
        'inapasarnormas',
        'inamaspracticas',
        'inatrabajodenoche',
        'inapausas',
        'inatrabajodiadesca',
        'inafinsemdesc',
        'inaencasapiensotra',
        'inadiscutofamilia',
        'inaasuntosencasa',
        'inapocotiempofami',
        'inapermitehabilidad',
        'inapermiteconocimi',
        'inapermiteaprender',
        'inamiscapacidades',
        'inapausasnecesito',
        'inatrabajodiario',
        'inadecivelocidad',
        'inacambiarordenact',
        'inaatenderasunpers',
        
            'inacambiosbeneficio',
    'inaexplicancambios',
    'inapuedodarsugeren',
    'inaencuentamisideas',
    'inacambiosdificultan',
    'inaclaridadfunciones',
    'inadecisionesatomar',
    'inaresultadoslograr',
    'inaefectoenempresa',
    'inaexplicanobjetivos',
    'inaorientaciontraba',
    'inaresolverasuntos',
    'inaasiscapacitacion',
    'inarecibocapacitaci',
    'inarecibocapaciayuda',
    'inajefeintrucciones',
    'inajefeayudaorganiz',
    'inajefemispuntosvist',
    'inajefeanima',
    'inajefedistribuye',
    'inajefecomunica',
    'inajefeorienracion',
    'inajefeayudaprogres',
    'inajefeayudasentime',
    'inajefesolucionar',
    'inajefeconfio',
    'inajefeescucha',
    'inajefeapoyo',
    'inaagradaambiente',
    'inagruporespeto',
    'inaconfiocompaneros',
    'inaagustocompaneros',
    'inagrupomaltrata',
    'inasolucionacompa',
    'inaintegraciongrp',
    'inagrupounido',
    'inasentirpartegrupo',
    'inatrabajogrupo',
    'inagrupodeacuerdo',
    'inagrupoayuda',
    'inaapoyounootros',
    'inaescuchanproble',
    'inainfhagobien',
    'inainfmejorar',
    'inainfrendimiento',
    'inaevaluantrabajo',
    'inainfatiempomejora',
    'inaempconfiantrab',
    'inaemppaganatiempo',
    'inapagoofrecido',
    'inapagomerezco',
    'inaposibprogresar',
    'inahacerbienprog',
    'inaempbienestartrab',
    'inatrabajoestable',
    'inatrabsentirbien',
    'inasientoorgullo',
    'inahablobienempres',
    'inaatencionausuarios' ,
    'inausuenojados',
    'inausupreocupados',
    'inausutristes',
    'inausuenfermos',
    'inausuneceayuda',
    'inausumemaltratan',
    'inaususentimidistin',
    'inasituaviolencia',
    'inaexigedolorosas',
    'inasoyjefe' ,
    'inacomuntarde',
    'inairrespetuosos',
    'inadificorganiza',
    'inaguardansilencio',
    'inadificlogro',
    'inainforirrespet',
    'inapocacooperacio',
    'inapocodesempeno',
    'inacolabignoran'
    
    ];

    protected $table = 'intralaboral_a';
    protected $primaryKey = 'inaid';
    public $timestamps = false;
}

