<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class formatoB extends Model
{

    protected $fillable = [
        'inbidempleado',
        'inbruido',
        'inbfrio',
        'inbcalor',
        'inbairefresco',
        'inbluz',
        'inbcomodo',
        'inbsustanquimicas',
        'inbesfuerzofisico',
        'inbequiposcomodos',
        'inbanimalesplantas',
        'inbpreoaccidente',
        'inblugarlimpio',
        'inbtiempoadicional',
        'inbalcanzatiempo',
        'inbtrabajasinparar',
        'inbesfuerzomental',
        'inbexigeconcentrado',
        'inbexigememoria',
        'inbhacercalculos',
        'inbpqnosdetalles',
        'inbtrabajonoche',
        'inbtomarpausas',
        'inbtrabajodiadesca',
        'inbfinsemdesc',
        'inbencasapiensotra',
        'inbdiscutofamilia',
        'inbasuntosencasa',
        'inbpocotiempofami',
        'inbhacercosasnuevas',
        'inbpermitehabilidad',
        'inbpermiteconocimi',
        'inbpermiteaprender',
        'inbpausasnecesito',
        'inbtrabajodiario',
        'inbdecivelocidad',
        'inbcambiarordenact',
        'inbatenderasunpers',
        'inbexplicancambios',
        'inbpuedodarsugeren',
        'inbencuentamisideas',
        'inbclaridadfunciones',
        'inbdecisionesatomar',
        'inbresultadoslograr',
        'inbexplicanobjetivos',
        'inbinfquienresolver',
        'inbasiscapacitacion',
        'inbrecibocapacitaci',
        'inbrecibocapaciayuda',
        'inbjefeayudaorganiz',
        'inbjefemispuntosvist',
        'inbjefeanima',
        'inbjefedistribuye',
        'inbjefecomunica',
        'inbjefeorienracion',
        'inbjefeayudaprogres',
        'inbjefeayudasentime',
        'inbjefesolucionar',
        'inbjeferespeto',
        'inbjefeconfio',
        'inbjefeescucha',
        'inbjefeapoyo',
        'inbagradaambiente',
        'inbgruporespeto',
        'inbconfiocompaneros',
        'inbagustocompaneros',
        'inbgrupomaltrata',
        'inbsolucionacompa',
        'inbgrupounido',
        'inbtrabajogrupo',
        'inbgrupodeacuerdo',
        'inbgrupoayuda',
        'inbapoyounootros',
        'inbescuchanproble',
        'inbinfhagobien',
        'inbinfmejorar',
        'inbinfrendimiento',
        'inbevaluantrabajo',
        'inbinfatiempomejora',
        'inbemppaganatiempo',
        'inbpagoofrecido',
        'inbpagomerezco',
        'inbposibprogresar',
        'inbhacerbienprog',
        'inbempbienestartrab',
        'inbtrabajoestable',
        'inbtrabsentirbien',
        'inbsientoorgullo',
        'inbhablobienempres',
        'inbatencionausuarios',
        'inbusuenojados',
        'inbusupreocupados',
        'inbusutristes',
        'inbusuenfermos',
        'inbusuneceayuda',
        'inbusumemaltratan',
        'inbsituaviolencia',
        'inbexigedolorosas',
        'inbexpretristeza' 
    
    ];

    protected $table = 'intralaboral_b';
    protected $primaryKey = 'inbid';
    public $timestamps = false;
}

