<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class valoracionFisica extends Model
{

    protected $fillable = [
        'vafidempresa' ,
        'vafidarea' ,
        'vafidnombre' ,
        'vafsede' ,
        'vafpeso' ,
        'vaftalla' ,
        'vafimc' ,
        'vafperimetro' ,
        'vafp0' ,
        'vafp1' ,
        'vafp2' ,
        'vaftestbiering' ,
        'vaftestpuenteder' ,
        'vaftestpuenteizq' ,
        'vaftestresistronco' ,
        'vaftestflextronco' ,
        'vaftestmovhombder' ,
        'vaftestmovhombizq' ,
        'vafcedula' ,
        'vafsexo',
        'vafgruposanguineo',
        'vaftelefono',
        'vafciudad',
        'vafedad',
        'vafcorreo',
        'vafcargo',
        'vaffecha',
        'vafcs01',
        'vafcs02',
        'vafcs03',
        'vafcs04',
        'vafcs05',
        'vafcs06',
        'vafcs07',
        'vafcs08',
        'vafcs09',
        'vafcs10',
        'vafcs11',
        'vafcs12',
        'vafcs13',
        'vafcs14',
        'vafcs15',
        'vafcs16',
        'vafcs17',
        'vafcs18',
        'vafcs19',
        'vafcs20',
        'vafcs21',
        'vafcancer_opc',
        'vafcancer_var',
        'vafhiper_arte_opc',
        'vafhiper_arte_var',
        'vafasma_opc',
        'vafasma_var',
        'vafcardio_opc',
        'vafcardio_var',
        'vafdiabet_opc',
        'vafdiabet_var',
        'vafalergia_opc',
        'vafalergia_var',
        'vafartritis_opc',
        'vafartritis_var',
        'vafem_opc',
        'vafem_var',
        'vafer_opc',
        'vafer_var',
        'vafmujer40_opc',
        'vafmujer40_var',
        'vafhombre40_opc',
        'vafhombre40_var',
        'vafdiscapacidad_opc',
        'vafdiscapacidad_var',
        'vaf_familiap01_opc',
        'vaf_familiap02_opc',
        'vaf_familia_num',
        'vaf_actifisip01_opc',
        'vaf_actifisip02_opc',
        'vaf_actifisi_num',
        'vaf_nutricionp01_opc',
        'vaf_nutricionp02_opc',
        'vaf_nutricionp03_opc',
        'vaf_nutricionp03_var',
        'vaf_tabacop01_opc',
        'vaf_tabacop02_opc',
        'vaf_tabacop02_var',
        'vaf_alcoholp01_opc',
        'vaf_alcoholp02_opc',
        'vaf_alcoholp03_opc',
        'vaf_suenop01_opc',
        'vaf_suenop02_opc',
        'vaf_suenop03_opc',
        'vaf_tipop01_opc',
        'vaf_tipop02_opc',
        'vaf_introspep01_opc',
        'vaf_introspep02_opc',
        'vaf_introspep03_opc',
        'vaf_condup01_opc',
        'vaf_condup02_opc',
        'vaf_otrasdp01_opc',
        'vaf_otrasdp02_opc',
        'vaf_otrasdp03_opc',
        'vaf_nutricion_num',
        'vaf_tabaco_num',
        'vaf_alcohol_num',
        'vaf_sueno_num',
        'vaf_tipo_num',
        'vaf_introspe_num',
        'vaf_condu_num',
        'vaf_otrasd_num',
        'vaf_fantastico_total',
        'vafAF_p01',
        'vafAF_p02',
        'vaf_fecha_creacion'
        
    ];

    protected $table = 'valoracionfisica';
    protected $primaryKey = 'vafid';
    public $timestamps = false;
}
